config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	get '/auth/venmo/callback' => 'users/omniauth_callbacks#venmo'

  root to: 'dashboards#index'

  resources :landings, only: [:index]

  resources :properties do
    resources :issues, except: [:index] do
      post :fix
    end
    resources :utilities do
      post :pay
    end
    resources :rental_terms, only: [:new, :create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update]

  resources :forums, only: [:show, :index] do
    resources :posts, only: [:show, :new, :create]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :posts
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :authenticate_user!

  respond_to :html

  def index
    @forums = Forum.all

    respond_with(@forums)
  end

  def show
    @forum = Forum.find(params[:id])

    respond_with(@forum)
  end
end

app/views/forums/index.html.haml
%h1 Forums

- @forums.each do |forum|
  %h3= link_to forum.name, forum
  %p= pluralize(forum.posts.count, 'post')

app/views/forums/show.html.haml
%h1= @forum.name

- if @forum.posts.any?
  - @forum.posts.each do |post|
    %h3= link_to post.title, forum_post_path(@forum, post)
    %p= pluralize(post.comments.count, 'comment')
- else
  %p No posts yet.

= link_to 'New Post', new_forum_post_path(@forum), class: 'btn btn-primary'
= link_to 'Back', forums_path, class: 'btn btn-default'