config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	get '/auth/venmo/callback' => 'users/omniauth_callbacks#venmo'

  root to: 'dashboards#index'

  resources :landings, only: [:index]

  resources :properties do
    resources :issues, except: [:index] do
      post :fix
    end
    resources :utilities do
      post :pay
    end
    resources :rental_terms, only: [:new, :create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update]

  resources :forums, only: [:show, :index] do
    resources :posts, only: [:show, :new, :create]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/utility.rb
class Utility < ActiveRecord::Base
  belongs_to :property

  has_many :dues

  def per_occupant_cost
    self.cost / self.property.current_occupants.count
  end
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  before_action :authenticate_user!

  respond_to :html

  def index
    @property = Property.find(params[:property_id])

    respond_with(@property)
  end

  def show
    @utility = Utility.find(params[:id])

    respond_with(@utility)
  end

  def new
    @utility = Utility.new
    @property = Property.find(params[:property_id])

    respond_with(@utility, @property)
  end

  def create
    @utility = Utility.new(utility_params)
    @property = Property.find(params[:property_id])
    @utility.property_id = @property.id

    if @utility.save
      occupants = @property.current_occupants
      occupants.each do |occupant|
	Due.create(
	  user_id: occupant.id,
	  utility_id: @utility.id,
	  amount: @utility.cost / occupants.count
	)
      end

      redirect_to property_utilities_path(@property), notice: 'Utility added successfully.'
    else
      flash[:alert] = @utility.errors.full_messages.join(', ')
      respond_with(@utility)
    end
  end

  def pay
    due = Due.find_by(user_id: current_user.id, utility_id: params[:utility_id])
    due.paid = true
    due.save

    redirect_to property_utilities_path(current_user.current_property),
      notice: "#{due.utility.provider} bill paid."
  end

private

  def utility_params
    params.require(:utility).permit(:provider, :due_by, :cost)
  end
end

app/views/utilities/index.html.haml
%h1.quicksand.utilities Utilities

- if current_user.has_dues?
  .payment_button_pos
    %span
      %a.btn.btn-lg.btn-primary.pomegranate.payment_button
        %i.fa.fa-money
        %span= raw "&nbsp;Pay #{number_to_currency(current_user.current_amount_due, unit: '$')}"

.row.dues_container
  - if current_user.has_dues?
    - current_user.current_dues.each do |due|
      .col-md-3.col-sm-4.col-xs-6
        .thumb-dummy
        .thumbnail.carrot.clouds.quicksand
          .vcenter
            %h3.quicksand= due.utility.provider
            %p= "#{number_to_currency(due.utility.per_occupant_cost, unit: '$')} due by #{due.utility.due_by.strftime('%e %B')} (#{number_to_currency(due.utility.cost, unit: '$')} total)"
          %span.pay
            = link_to property_utility_pay_path(@property, due.utility), class: 'clouds', method: :post do
              %span.fa.fa-check
              %span &nbsp;Mark as Paid

  - else
    .col-md-12
      %p No dues currently.

  - current_user.past_dues.each do |due|
    .col-md-3.col-sm-4.col-xs-6
      .thumb-dummy
      .thumbnail.nephritis.clouds.quicksand
        .vcenter
          %p= "Paid #{number_to_currency(due.utility.per_occupant_cost, unit: '$')} for #{due.utility.provider} on #{due.updated_at.strftime('%e %B')}"
- if current_user.has_dues?
  .row.dues_summary
    .col-md-6
      .summary_card
        %h4.quicksand.summary_information= "You currently owe #{number_to_currency(current_user.current_amount_due, unit: '$')}."
        %ul.clouds
          - current_user.current_dues.each do |due|
            %li= "#{due.utility.provider} - #{number_to_currency(due.amount, unit: '$')}"

.row.center
  = link_to 'Add Utility', new_property_utility_path(@property), class: 'btn btn-primary btn-lg pomegranate clouds payment_button'

app/views/utilities/new.html.haml
%h1 Add Utility

= simple_form_for [@property, @utility] do |f|
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-building
      %input.form-control{type: "text", name: "utility[provider]", placeholder: "Provider", required: true}
  .form-group
    #datepicker.input-daterange.input-group
      %span.input-group-addon
        %i.fa.fa-calendar
      %input.input-sm.form-control{ type: "text", name: 'utility[due_by]', placeholder: 'Due Date', required: true, data: { provide: 'datepicker', date: { format: 'dd/mm/yyyy' } }}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-dollar
      %input.form-control{type: "text", name:"utility[cost]", placeholder: "Cost"}
  .form-group{ style: 'text-align: center; margin-top: 15px;' }
    %input.btn.btn-primary.property-btn{ type: 'submit' }