config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	get '/auth/venmo/callback' => 'users/omniauth_callbacks#venmo'

  root to: 'dashboards#index'

  resources :landings, only: [:index]

  resources :properties do
    resources :issues, except: [:index] do
      post :fix
    end
    resources :utilities do
      post :pay
    end
    resources :rental_terms, only: [:new, :create, :edit, :update]
  end

  resources :users, only: [:show, :edit, :update]

  resources :forums, only: [:show, :index] do
    resources :posts, only: [:show, :new, :create]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user

  has_many :rental_terms
  has_many :users, through: :rental_terms
  has_many :issues
  has_many :utilities

	validates :address, :landlord_name, :rent, presence: true

  has_attached_file :image, default_url: 'house_placeholder.jpg'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def current_occupants
    end_field = RentalTerm.arel_table[:end_date]
    property_field = RentalTerm.arel_table[:property_id]
    RentalTerm.where(end_field.gteq(Date.current).and(property_field.eq(self.id))).map(&:user).uniq
  end

  def is_current_occupant?(user)
    self.current_occupants.include?(user)
  end

  def current_term_for(user)
    self.rental_terms.where(user: user).order(end_date: :desc).first
  end

  def has_terms?
    self.rental_terms.count > 0
  end

  def average_property_rating
    self.rental_terms.pluck(:property_rating).reduce(:+) / self.rental_terms.count
  end

  def average_landlord_rating
    self.rental_terms.pluck(:landlord_rating).reduce(:+) / self.rental_terms.count
  end

  def comments
    self.rental_terms.pluck(:comments)
  end

  def fixed_issues
    self.issues.where(fixed: true)
  end

  def outstanding_issues
    self.issues.where(fixed: false)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	before_action :authenticate_user!

	respond_to :html

	def index
		@properties = Property.all

		respond_with(@properties)
	end

	def show
		@property = Property.find(params[:id])

		respond_with(@property)
	end

	def new
		@property = Property.new

		respond_with(@property)
	end

	def create
		@property = Property.new(property_params)
		@property.user_id = current_user.id

		if @property.save
			redirect_to @property, notice: 'Property added successfully.'
		else
			flash[:alert] = @property.errors.full_messages.join(', ')
			respond_with(@property)
		end
	end

	def edit
		@property = Property.find(params[:id])

		respond_with(@property)
	end

	def update
		@property = Property.find(params[:id])
		@property.update_attributes(property_params)

    if @property.save
      redirect_to @property, notice: 'Property updated successfully.'
    else
      flash[:alert] = @property.errors.full_messages.join(', ')
      respond_with(@property)
    end
	end

private

	def property_params
		params.require(:property).permit(:name, :address, :description,
																		 :landlord_name, :landlord_phone,
																		 :landlord_email, :image, :rent)
	end

	#def rental_term_params
		#params.require(:rental_term).permit(:end_date, :start_date, :comments,
																				#:property_rating, :landlord_rating)
	#end
end

app/views/properties/_form.html.haml
= simple_form_for @property do |f|
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-home
      %input.form-control{type: "text", value: @property.name, name: "property[name]", placeholder: "Property Name", required: true}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-building
      %input#address.form-control{type: "text", value: @property.address, name: "property[address]", placeholder: "Address", required: true}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-pencil-square
      %textarea#description.form-control{name: "property[description]", placeholder: "Description"}= @property.description
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-male
      %input#landlord_name.form-control{type: "text", value: @property.landlord_name, name: "property[landlord_name]", placeholder: "Landlord Name"}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-envelope
      %input#landlord_email.form-control{type: "text", value: @property.landlord_email, name: "property[landlord_email]", placeholder: "Landlord Email", required: true}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-phone
      %input#phone_number.form-control{type: "text", value: @property.landlord_phone, name: "property[landlord_phone]", placeholder: "Landlord Phone Number"}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-dollar
      %input.form-control{type: "text", value: @property.rent, name: "property[rent]", placeholder: "Rent"}

  .form-group
    = f.file_field :image

  .form-group{ style: 'text-align: center; margin-top: 15px;' }
    %input.btn.btn-primary.property-btn{ type: 'submit' }
    = link_to 'Cancel', properties_path, class: 'btn btn-default'

app/views/properties/_property.html.haml
%ul#dashboard-tabs.nav.nav-tabs.dashboard{ role: "tablist" }
  %li.active
    %a{ href: "#home", data: { toggle: "tab" }} Summary
  %li
    %a{ href: "#issues", data: { toggle: "tab" }} Issues
  %li
    %a{ href: "#roommates", data: { toggle: "tab" }} Roommates

.tab-content
  #home.tab-pane.active
    .row
      .col-md-8
        .row
          .col-md-4.rental_ratings_container
            .square
              %h2.rating.clouds Rental Unit Rating
              %h3.rating
                - if property.has_terms?
                  - property.average_property_rating.round.times do |x|
                    %span.fa.fa-star.yellow
                - else
                  %p Property not yet rated
          .col-md-4.landlord_ratings_container
            .square
              %h2.rating.clouds Landlord Rating
              %h3.rating
                - if property.has_terms?
                  - property.average_landlord_rating.round.times do |x|
                    %span.fa.fa-star.yellow
                - else
                  %p Property not yet rated

        - if property.comments.any?
          .comments_container
            %h3.comments Comments:
            - property.rental_terms.each do |term|
              %p= "#{term.user.name}:"
              %blockquote
                %p.comments= term.comments
        .property-buttons
          = link_to edit_property_path(property), class: 'btn btn-primary' do
            %span.fa.fa-pencil &nbsp;Edit
          - if property.is_current_occupant?(current_user)
            = link_to 'Edit Current Rental Term', edit_property_rental_term_path(property, property.current_term_for(current_user)), class: 'btn btn-success'
          = link_to 'Add Rental Term', new_property_rental_term_path(property), class: 'btn btn-default'

      .col-md-4.summary_details
        %h3.house_name.clouds= property.name
        .img_circle_holder{ align: "center" }
        %p.address_information.clouds= property.address
        %hr
        %h3.landlord_name.clouds= property.landlord_name
        %p.landlord_email.clouds= property.landlord_email
        %p.landlord_phone_number.clouds= property.landlord_phone
        %hr
        %h3.clouds= "#{number_to_currency(property.rent, unit: '$')} per month"

  #issues.tab-pane
    .row.issues_container
      - if property.issues.empty?
        .col-md-12
          %p No issues yet.
      - else
        - property.outstanding_issues.each do |issue|
          .col-md-3.col-sm-4.col-xs-6
            .thumb-dummy
            .thumbnail.carrot.clouds.quicksand= issue.description
            .thumbnail.carrot.clouds.quicksand.hide
              = "Reported by #{issue.user.first_name}"
              %span.fix
                = link_to property_issue_fix_path(property, issue), class: 'clouds', method: :post do
                  %span.fa.fa-check
                  %span &nbsp;Mark as Fixed

        - property.fixed_issues.each do |issue|
          .col-md-3.col-sm-4.col-xs-6
            .thumb-dummy
            .thumbnail.nephritis.clouds.quicksand= issue.description
            .thumbnail.nephritis.clouds.quicksand.hide
              = "Reported by #{issue.user.first_name}"

    .row
      .col-md-12.center
        = link_to 'Report an Issue', new_property_issue_path(property), class: 'btn btn-primary'

  #roommates.tab-pane
    - if property.has_terms? and property.current_occupants.any?
      - property.current_occupants.each do |user|
        = render 'users/user', user: user
    - else
      %p No roommates listed.

app/views/properties/edit.html.haml
.well
  %h1.title Edit Property
  %hr
  = render 'properties/form'

app/views/properties/index.html.haml
%h1.quicksand.center.property_style{ style: 'margin-bottom: 5px;' } Properties

.row.properties_container
  - if @properties.empty?
    %p No properties, yet.
  - else
    - @properties.each do |property|
      .col-md-6.col-sm-6.col-xs-6.center{ style: 'margin-top: 15px;' }
        = link_to property do
          .thumbnail
            = image_tag property.image.url, class: 'img-rounded'
          .cover.carrot.clouds.quicksand
            .row
              .col-md-12
                %p= property.address
                %p= property.landlord_name

.row
  .col-md-12.center{ style: 'margin-top: 15px;' }
    = link_to 'Add Property', new_property_path, class: 'btn btn-lg asbestos clouds'

app/views/properties/new.html.haml
.well
  %h1.title Add New Property
  %hr
  = simple_form_for @property do |f|
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-home
        %input.form-control{type: "text", name: "property[name]", placeholder: "Property Name", required: true}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-building
        %input#address.form-control{type: "text", name: "property[address]", placeholder: "Address", required: true}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-pencil-square
        %textarea#description.form-control{name: "property[description]", placeholder: "Description"}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-male
        %input#landlord_name.form-control{type: "text", name: "property[landlord_name]", placeholder: "Landlord Name"}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-envelope
        %input#landlord_email.form-control{type: "text", name: "property[landlord_email]", placeholder: "Landlord Email", required: true}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-phone
        %input#phone_number.form-control{type: "text", name:"property[landlord_phone]", placeholder: "Landlord Phone Number"}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-dollar
        %input.form-control{type: "text", name:"property[rent]", placeholder: "Rent"}

    .form-group
      #datepicker.input-daterange.input-group
        %span.input-group-addon
          %i.fa.fa-calendar
        %input.input-sm.form-control{ type: "text", name: 'rental_term[start_date]', placeholder: 'Lease Start', required: true, data: { provide: 'datepicker', date: { format: 'dd/mm/yyyy' } }}
        %span.input-group-addon to
        %input.input-sm.form-control{ type: "text", name: "rental_term[end_date]", placeholder: 'Lease End', required: true, data: { provide: 'datepicker', date: { format: 'dd/mm/yyyy' }}}

    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-edit
        %textarea.form-control{name: 'rental_term[comments]', placeholder: 'Comments on rental'}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-star
        %input.form-control{type: "text", name:"rental_term[property_rating]", required: true, placeholder: "Property Rating (1-5)"}
    .form-group
      .input-group
        .input-group-addon
          %i.fa.fa-heart
        %input.form-control{type: "text", name:"rental_term[landlord_rating]", required: true, placeholder: "Landlord Rating (1-5)"}

    .form-group
      = f.file_field :image

    .form-group{ style: 'text-align: center; margin-top: 15px;' }
      %input.btn.btn-primary.property-btn{ type: 'submit' }
      = link_to 'Cancel', properties_path, class: 'btn btn-default'

app/views/properties/show.html.haml
= render 'properties/property', property: @property